apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-database-config
data:
  POSTGRES_DB: papermerge
  POSTGRES_USER: papermerge

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-database-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: pmg-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-database
  template:
    metadata:
      labels:
        app: papermerge-database
    spec:
      containers:
        - name: papermerge-database
          image: postgres:17-alpine
          envFrom:
            - configMapRef:
                name: papermerge-database-config
            - secretRef:
                name: papermerge-database-secret
          volumeMounts:
            - name: papermerge-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: papermerge-storage
          hostPath:
            path: /postgres-data
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: papermerge-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: papermerge-database