apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-ocr-config
data:
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermergedatabase:5432/papermerge
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  OCR_WORKER_ARGS: "-Q ocr -c 2"

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-ocr-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 2e8817266261610810596a50b8f4a8c5
  AWS_SECRET_ACCESS_KEY: a503071debfa3ac0c1de1cd79f

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-ocr
  template:
    metadata:
      labels:
        app: papermerge-ocr
    spec:
      containers:
        - name: papermerge-ocr
          image: papermerge/ocrworker:0.3.1
          envFrom:
            - configMapRef:
                name: papermerge-ocr-config
            - secretRef:
                name: papermerge-ocr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: papermerge-ocr
spec:
  selector:
    app: ocr
  ports:
    - port: 80
      targetPort: 8080