apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-config
data:
  POSTGRES_DB: papermerge
  POSTGRES_USER: papermerge
  MINIO_ROOT_USER: 2e8817266261610810596a50b8f4a8c5
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"
  OCR_WORKER_ARGS: "-Q ocr -c 2"
  PAPERMERGE__AUTH__USERNAME: admin
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: pmg-secret
  MINIO_ROOT_PASSWORD: a503071debfa3ac0c1de1cd79f
  AWS_ACCESS_KEY_ID: 2e8817266261610810596a50b8f4a8c5
  AWS_SECRET_ACCESS_KEY: a503071debfa3ac0c1de1cd79f
  PAPERMERGE__AUTH__PASSWORD: secret
  PAPERMERGE__SECURITY__SECRET_KEY: 8aa9127e904324e1d93c2b68483a327c3b5be964dd161e3e4df8dbca0443ec21

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
        - name: papermerge
          image: papermerge/papermerge:3.3.1
          envFrom:
            - configMapRef:
                name: papermerge-config
            - secretRef:
                name: papermerge-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: papermerge-data
              mountPath: /var/media/pmg
      volumes:
        - name: papermerge-data
          hostPath:
            path: /papermerge-data
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: papermerge
spec:
  type: LoadBalancer
  selector:
    app: papermerge
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80