apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-s3worker-config
data:
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermergedatabase:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-s3worker-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 2e8817266261610810596a50b8f4a8c5
  AWS_SECRET_ACCESS_KEY: a503071debfa3ac0c1de1cd79f

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-s3worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-s3worker
  template:
    metadata:
      labels:
        app: papermerge-s3worker
    spec:
      containers:
        - name: papermerge-s3worker
          image: papermerge/s3worker:0.4.3
          envFrom:
            - configMapRef:
                name: papermerge-s3worker-config
            - secretRef:
                name: papermerge-s3worker-secret
          volumeMounts:
            - name: s3worker-storage
              mountPath: /var/media/pmg
      volumes:
        - name: s3worker-storage
          hostPath:
            path: /data/s3worker-storage
            type: DirectoryOrCreate
